version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3"
sphinx:
  {%- if not cookiecutter.prefix %}
  configuration: modules/{{ cookiecutter.package_name }}/doc/conf.py
  {%- else %}
  configuration: doc/conf.py
  {%- endif %}
